sudo: false
language: rust
rust:
  - nightly
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - cargo +nightly test
  - cargo +nightly check --manifest-path examples/example_1/Cargo.toml
  - cargo +nightly test -Z minimal-versions
  - cargo +nightly check -Z minimal-versions --manifest-path examples/example_1/Cargo.toml
