sudo: false
language: rust
rust:
- nightly
notifications:
  email:
    on_success: never
    on_failure: never
script:
- |
  rustup run nightly cargo test &&
  rustup run nightly cargo check --manifest-path examples/example_1/Cargo.toml # TODO test with minimal versions
